### ISSUE TITLE
release?

### ISSUE THREAD

**Issue by johannesgreiner** [qiskit-research/qiskit-research#31]
are you planning on a release of qiskit-research so users can just `pip install` ?
I keep advertising qiskit-research , this would be great for increased ease of use

**Comment by kevinsung** [comment]
Currently a release is not in the plans.

qiskit-research contains two kinds of code. The first kind is code associated with running a research experiment, and there is no need to be able to install that code from PyPI. The second kind of code are common utilities that are used by research experiments, currently all residing in the `utils/` directory. It could be useful to be able to install this code from PyPI, but much of this code is transient because we intend to move it to Qiskit Terra or one of the application libraries such as Qiskit Nature.

In the future it may turn out that some useful utilities will stabilize and remain in qiskit-research. At that time it may be appropriate to plan for a release, but right not we don't feel that the library is mature enough.

**Comment by johannesgreiner** [comment]
closing & you can reopen if appropriate
